[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "babel>=2.17.0",
    "fastapi>=0.117.1",
    "jinja2>=3.1.6",
    "uvicorn>=0.37.0",
]
